name: Insecure Workflow Test
on: pull_request_target

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out PR code from fork with explicit SHA
      - name: Check out PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}


      - name: Make deploy_script.sh executable
        run: chmod +x ./deploy_script.sh    

      # Step 2: Run deployment with a secret
      - name: Deploy with Secret Key
        run: ./deploy_script.sh
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
