name: Insecure Workflow Test
on: pull_request_target

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out PR code
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Step 2: Run deployment with a secret
      - name: Deploy with Secret Key
        run: ./deploy_script.sh
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
